#!/usr/bin/env python3
"""Generate immutable run provenance metadata for every results/ subdirectory.

Phase 0 evidence freeze: each result directory gets a run_provenance.json capturing
immutable run ID, git commit SHA, environment lock hash, input hash, exact command,
random seeds, output schema, and frozen analysis spec reference.

This script is READ-ONLY with respect to existing artifacts: it only creates new
run_provenance.json files and never modifies or deletes existing results.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path("/home/cunyuliu/pc_cng_research")
RESULTS_DIR = REPO_ROOT / "results"
PROVENANCE_FILENAME = "run_provenance.json"
SCHEMA_VERSION = "1.0"

# Files that are generated by this script or are logs; skip when hashing content
# but still record their existence in output schema.
SKIP_HASH_SUFFIXES = {".log", ".pid"}
SKIP_HASH_NAMES = {PROVENANCE_FILENAME, "nmi_audit_status.json", "nohup.out"}


def run(cmd: list[str], cwd: Path | None = None, timeout: int = 30) -> str:
    try:
        r = subprocess.run(
            cmd, cwd=cwd, capture_output=True, text=True, timeout=timeout, check=False
        )
        return r.stdout.strip() if r.returncode == 0 else ""
    except Exception:
        return ""


def git_commit_sha() -> str:
    return run(["git", "rev-parse", "HEAD"], cwd=REPO_ROOT) or "unknown"


def git_branch() -> str:
    return run(["git", "rev-parse", "--abbrev-ref", "HEAD"], cwd=REPO_ROOT) or "unknown"


def env_lock_hash() -> str:
    """Hash of conda environment spec (not full env to keep it fast)."""
    env_name = os.environ.get("CONDA_DEFAULT_ENV", "pc_cng_gpu")
    spec = run(
        ["conda", "env", "export", "--name", env_name, "--no-builds"],
        timeout=60,
    )
    if not spec:
        # Fallback: hash requirements.txt
        req = REPO_ROOT / "chem_negative_sampling" / "requirements.txt"
        if req.exists():
            spec = req.read_text(errors="replace")
    return hashlib.sha256(spec.encode("utf-8")).hexdigest()[:16]


def hash_file(path: Path) -> str | None:
    try:
        h = hashlib.sha256()
        with open(path, "rb") as f:
            for chunk in iter(lambda: f.read(65536), b""):
                h.update(chunk)
        return h.hexdigest()[:16]
    except Exception:
        return None


def hash_directory(dirpath: Path) -> str:
    """Content hash of all non-log files in directory (for immutable run ID)."""
    h = hashlib.sha256()
    files = sorted(
        p for p in dirpath.rglob("*")
        if p.is_file()
        and p.name not in SKIP_HASH_NAMES
        and p.suffix not in SKIP_HASH_SUFFIXES
    )
    for p in files:
        rel = str(p.relative_to(dirpath))
        h.update(rel.encode("utf-8"))
        try:
            with open(p, "rb") as f:
                for chunk in iter(lambda: f.read(65536), b""):
                    h.update(chunk)
        except Exception:
            h.update(b"<unreadable>")
    return h.hexdigest()[:16]


def extract_command(dirpath: Path, dirname: str) -> str:
    """Try to recover the exact command from commands.log or directory name."""
    cmd_log = dirpath / "commands.log"
    if cmd_log.exists():
        try:
            content = cmd_log.read_text(errors="replace").strip()
            if content:
                # Take first non-empty line as the command
                return content.splitlines()[0][:500]
        except Exception:
            pass
    # Fallback: infer from directory name
    return f"<inferred from directory name: {dirname}>"


def extract_seeds(dirpath: Path) -> list[int]:
    """Extract random seeds from config files or seed files."""
    seeds: list[int] = []
    # Look for seed patterns in JSON configs
    for p in dirpath.glob("*.json"):
        try:
            data = json.loads(p.read_text(errors="replace"))
            if isinstance(data, dict):
                for key in ("seed", "random_seed", "n_seeds", "base_seed"):
                    if key in data and isinstance(data[key], int):
                        seeds.append(data[key])
                # Check nested configs
                if "config" in data and isinstance(data["config"], dict):
                    for key in ("seed", "random_seed", "base_seed"):
                        if key in data["config"] and isinstance(data["config"][key], int):
                            seeds.append(data["config"][key])
        except Exception:
            continue
    # Deduplicate while preserving order
    seen: set[int] = set()
    unique: list[int] = []
    for s in seeds:
        if s not in seen:
            seen.add(s)
            unique.append(s)
    return unique


def output_schema(dirpath: Path) -> dict:
    """Categorize output files by type."""
    schema: dict[str, list[str]] = {
        "json": [],
        "csv": [],
        "png": [],
        "log": [],
        "other": [],
    }
    for p in sorted(dirpath.rglob("*")):
        if not p.is_file() or p.name in SKIP_HASH_NAMES:
            continue
        rel = str(p.relative_to(dirpath))
        suffix = p.suffix.lower().lstrip(".")
        if suffix in schema:
            schema[suffix].append(rel)
        elif suffix in ("jsonl", "npy", "npz", "pt", "pkl"):
            schema["other"].append(rel)
        else:
            schema["other"].append(rel)
    return {k: v for k, v in schema.items() if v}


def input_hash(dirpath: Path) -> str:
    """Hash of any input manifest or config referenced."""
    h = hashlib.sha256()
    found = False
    for name in ("input_manifest.json", "manifest.json", "config.json", "split_manifest.json"):
        p = dirpath / name
        if p.exists():
            try:
                h.update(p.read_bytes())
                found = True
            except Exception:
                pass
    return h.hexdigest()[:16] if found else ""


def frozen_analysis_spec(dirpath: Path) -> str:
    """Reference to frozen analysis spec if present."""
    for name in ("analysis_spec.json", "frozen_analysis_spec.json", "go_no_go.json"):
        p = dirpath / name
        if p.exists():
            return name
    return ""


def generate_for_directory(dirpath: Path) -> dict:
    dirname = dirpath.name
    return {
        "schema_version": SCHEMA_VERSION,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "run_id": hash_directory(dirpath),
        "git_commit_sha": git_commit_sha(),
        "git_branch": git_branch(),
        "env_lock_hash": env_lock_hash(),
        "conda_env": os.environ.get("CONDA_DEFAULT_ENV", "unknown"),
        "input_hash": input_hash(dirpath),
        "exact_command": extract_command(dirpath, dirname),
        "random_seeds": extract_seeds(dirpath),
        "output_schema": output_schema(dirpath),
        "frozen_analysis_spec": frozen_analysis_spec(dirpath),
        "nmi_audit_status_exists": (dirpath / "nmi_audit_status.json").exists(),
        "provenance_note": "Generated by Phase 0 evidence freeze; original artifacts unchanged",
    }


def main() -> int:
    if not RESULTS_DIR.exists():
        print(f"ERROR: {RESULTS_DIR} does not exist", file=sys.stderr)
        return 1

    n_created = 0
    n_skipped = 0
    n_errors = 0

    for entry in sorted(RESULTS_DIR.iterdir()):
        if not entry.is_dir():
            continue
        provenance_path = entry / PROVENANCE_FILENAME
        try:
            provenance = generate_for_directory(entry)
            provenance_path.write_text(
                json.dumps(provenance, indent=2, ensure_ascii=False) + "\n",
                encoding="utf-8",
            )
            n_created += 1
            print(f"  OK  {entry.name}")
        except Exception as e:
            n_errors += 1
            print(f"  ERR {entry.name}: {e}", file=sys.stderr)

    print(f"\nDone: {n_created} created, {n_skipped} skipped, {n_errors} errors")
    return 0 if n_errors == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
